FROM ubuntu

MAINTAINER Nicolas Lorin <androw95220@gmail.com>

RUN apt-get update && apt-get -y install default-jre && apt-get -y autoclean && apt-get -y clean && apt-get -y autoremove

ADD ./root/spark-1.6.1-bin-hadoop2.6.tgz /usr/local
ADD ./root/zeppelin-0.5.6-incubating-bin-all.tgz /usr/local
RUN cd /usr/local && ln -s spark-1.6.1-bin-hadoop2.6 spark && ln -s zeppelin-0.5.6-incubating-bin-all zeppelin

ADD scripts/*.sh /
ADD scripts/spark-defaults.conf /spark-defaults.conf

ENV SPARK_HOME /usr/local/spark

EXPOSE 8080 8081 
CMD ["bash"]
